# **Next word prediction LSTM model**

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

### Reading text file
- when reading file line breaks become newline characters('\n')

In [4]:
with open("data/Alice's Adventures in Wonderland by Lewis Carroll.txt", 'r', encoding='utf-8') as myfile:
    alices_dventures_txt = myfile.read()

In [5]:
alices_dventures_txt

"The Project Gutenberg eBook of Alice's Adventures in Wonderland\n    \nThis eBook is for the use of anyone anywhere in the United States and\nmost other parts of the world at no cost and with almost no restrictions\nwhatsoever. You may copy it, give it away or re-use it under the terms\nof the Project Gutenberg License included with this eBook or online\nat www.gutenberg.org. If you are not located in the United States,\nyou will have to check the laws of the country where you are located\nbefore using this eBook.\n\nTitle: Alice's Adventures in Wonderland\n\nAuthor: Lewis Carroll\n\n\n        \nRelease date: June 27, 2008 [eBook #11]\n                Most recently updated: June 26, 2025\n\nLanguage: English\n\nOther information and formats: www.gutenberg.org/ebooks/11\n\nCredits: Arthur DiBianca and David Widger\n\n\n*** START OF THE PROJECT GUTENBERG EBOOK ALICE'S ADVENTURES IN WONDERLAND ***\n\n[Illustration]\n\n\n\n\nAlice’s Adventures in Wonderland\n\nby Lewis Carroll\n\nTHE MILL

### Tokenizing

In [6]:
my_tokenizer = Tokenizer()
my_tokenizer.fit_on_texts([alices_dventures_txt])
total_words = len(my_tokenizer.word_index) + 1

In [7]:
my_tokenizer.word_index

{'the': 1,
 '”': 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'she': 7,
 'it': 8,
 'said': 9,
 'in': 10,
 'you': 11,
 'alice': 12,
 'was': 13,
 'that': 14,
 'i': 15,
 'as': 16,
 'her': 17,
 'with': 18,
 'at': 19,
 'on': 20,
 'all': 21,
 'had': 22,
 'this': 23,
 'for': 24,
 'be': 25,
 'not': 26,
 'or': 27,
 'so': 28,
 'very': 29,
 'little': 30,
 'but': 31,
 '“i': 32,
 'they': 33,
 'is': 34,
 'out': 35,
 'he': 36,
 'down': 37,
 'about': 38,
 'up': 39,
 'what': 40,
 'one': 41,
 'if': 42,
 'his': 43,
 'do': 44,
 'were': 45,
 'no': 46,
 'have': 47,
 'like': 48,
 'project': 49,
 'went': 50,
 'herself': 51,
 'them': 52,
 'by': 53,
 'again': 54,
 'know': 55,
 'then': 56,
 'could': 57,
 'would': 58,
 'gutenberg': 59,
 'when': 60,
 'any': 61,
 'thought': 62,
 'there': 63,
 'time': 64,
 'are': 65,
 'your': 66,
 'see': 67,
 'queen': 68,
 'into': 69,
 'me': 70,
 'off': 71,
 'an': 72,
 'king': 73,
 'its': 74,
 'did': 75,
 'who': 76,
 'began': 77,
 'other': 78,
 'mock': 79,
 'way': 80,
 'my': 81,
 'tu

### Sequence
- one line consider as a sequence

In [57]:
my_input_sequence = []
#x=1

# Let text file content into lines jher we used \n for seperateion because when we read a text file '\n' added at line seprations
# let iterate through the all lines

for line in alices_dventures_txt.split("\n"):
   
    print(f"\nLine {x}: ",line)
    #x=x+1
    # For each line adding tokenizing then result is numbered list for each waord in line
    # numbers/values assigned using above word_index
    token_list = my_tokenizer.texts_to_sequences([line])[0]
    #print(token_list)

    # now iterate through the each value in the current token_list
    for i in range(1, len(token_list)):
        # genrating cumulative adition lists 10 elts > 9 lists
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)

        # list of all n_greams
        my_input_sequence.append(my_n_gram_sequence)
    # print(my_input_sequence)
    # if x==5:
    #     break


Line 5:  The Project Gutenberg eBook of Alice's Adventures in Wonderland

Line 5:      

Line 5:  This eBook is for the use of anyone anywhere in the United States and

Line 5:  most other parts of the world at no cost and with almost no restrictions

Line 5:  whatsoever. You may copy it, give it away or re-use it under the terms

Line 5:  of the Project Gutenberg License included with this eBook or online

Line 5:  at www.gutenberg.org. If you are not located in the United States,

Line 5:  you will have to check the laws of the country where you are located

Line 5:  before using this eBook.

Line 5:  

Line 5:  Title: Alice's Adventures in Wonderland

Line 5:  

Line 5:  Author: Lewis Carroll

Line 5:  

Line 5:  

Line 5:          

Line 5:  Release date: June 27, 2008 [eBook #11]

Line 5:                  Most recently updated: June 26, 2025

Line 5:  

Line 5:  Language: English

Line 5:  

Line 5:  Other information and formats: www.gutenberg.org/ebooks/11

Line 5:  

Line 5:  

In [43]:
len(my_input_sequence)

28110

In [51]:
for i in range(10) : print(my_input_sequence[i])

[1, 49]
[1, 49, 59]
[1, 49, 59, 313]
[1, 49, 59, 313, 6]
[1, 49, 59, 313, 6, 817]
[1, 49, 59, 313, 6, 817, 406]
[1, 49, 59, 313, 6, 817, 406, 10]
[1, 49, 59, 313, 6, 817, 406, 10, 556]
[23, 313]
[23, 313, 34]


In [58]:
# Finding len of the longest line
max_sequence_len = max([len(seq) for seq in my_input_sequence])

# pad_sequence = every sequence is padded to length max_sequence_len, padding='pre' = prefix padding as 0s
input_sequences = np.array(pad_sequences(my_input_sequence, maxlen=max_sequence_len, padding='pre'))

In [59]:
max_sequence_len

18

In [60]:
input_sequences[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
       49], dtype=int32)

### Data splitting

In [62]:
# consider input_sequences[0] > [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 49]
# from 1st elt to 17th elt we get as X part then using that we are going to predict Y prt last elt always
# these is our features/X and labels/Y

In [64]:
X = input_sequences[:, :-1] # for all rows until -1 col except -1/last
y = input_sequences[:, -1] # last elt of each rows

In [65]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int32)

In [66]:
y[0]

np.int32(49)

In [67]:
y

array([ 49,  59, 313, ...,  38, 508, 491], shape=(28110,), dtype=int32)

In [69]:
# Converting y inot onhot encoding vec

In [71]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [75]:
y[0] # now 49 elt is 1, but all other 0

array([0., 0., 0., ..., 0., 0., 0.], shape=(3537,))

In [74]:
y[0][49]

np.float64(1.0)